const body = document.body;
const translations = {
  en: {
    'Saltar al contenido':'Skip to content','Navegación principal':'Main navigation','Funciones':'Features','Por qué registrar':'Why track','Capturas':'Screenshots','Idioma':'Language','Seleccionar idioma':'Select language','Cambiar tema':'Change theme','Abrir GeFi':'Open GeFi',
    'Finanzas personales, sin ruido':'Personal finance, without the noise','Tu dinero,':'Your money,','con contexto.':'with context.','Registrá cada movimiento, entendé tus hábitos y tomá decisiones con información real. GeFi reúne todo lo que pasa con tu dinero en un solo lugar.':'Track every transaction, understand your habits, and make decisions with real information. GeFi brings everything that happens with your money into one place.','Empezar ahora':'Get started','Ver cómo funciona':'See how it works','Características principales':'Main features','Funciona sin conexión':'Works offline','Sin costo':'Free to use','Datos bajo tu control':'Your data, under your control',
    'Vista real del resumen de GeFi':'Real view of the GeFi overview','Resumen financiero':'Financial overview','Flujo del mes':'Monthly cash flow','Gráfico decorativo de evolución mensual':'Decorative monthly trend chart','Todo actualizado':'Everything up to date','Balance visible':'Visible balance','En todo momento':'At all times','Registro inteligente':'Smart entry','“Hoy gasté 2.000” ✓':'“I spent 2,000 today” ✓','Beneficios de GeFi':'GeFi benefits','Una vista completa':'A complete view','de tu patrimonio':'of your net worth','Menos tiempo':'Less time','cargando movimientos':'logging transactions','Más claridad':'More clarity','para decidir':'to make decisions',
    'Lo que no registrás, no podés mejorarlo':'You cannot improve what you do not track','Cada movimiento':'Every transaction','cuenta una historia.':'tells a story.','Anotar no es controlar por controlar. Es convertir compras, ingresos y decisiones cotidianas en una imagen honesta de tu realidad financiera.':'Tracking is not about control for its own sake. It turns purchases, income, and everyday decisions into an honest picture of your financial reality.','Dejá de adivinar':'Stop guessing','Sabé cuánto tenés, dónde está y en qué se fue. Sin cuentas mentales ni saldos aislados.':'Know how much you have, where it is, and where it went. No mental math or isolated balances.','Detectá hábitos':'Spot patterns','Los pequeños gastos repetidos dejan de ser invisibles.':'Small recurring expenses stop being invisible.','Medí tu progreso':'Measure your progress','Compará meses y entendé si tus decisiones te acercan a tus objetivos.':'Compare months and see whether your decisions are moving you toward your goals.','Decidí antes':'Act sooner','Presupuestos y reportes te ayudan a actuar antes de que un desorden se convierta en problema.':'Budgets and reports help you act before disorder becomes a problem.',
    'Todo conectado':'Everything connected','Una sola app.':'One app.','Toda tu economía.':'Your entire financial life.','Registrá con lenguaje natural':'Log transactions naturally','Escribí o dictá “hoy gasté 2.000 en el supermercado”. GeFi interpreta fecha, monto, categoría y detalle.':'Type or say “I spent 2,000 at the supermarket today.” GeFi identifies the date, amount, category, and details.','Hoy gasté 2.000 en el supermercado':'I spent 2,000 at the supermarket today','Enviar ejemplo':'Send example','HOY':'TODAY','GASTO':'EXPENSE','Todo tu patrimonio':'Your full net worth','Cuentas, efectivo e inversiones se leen como una sola imagen, sin confundir transferencias con gastos.':'Accounts, cash, and investments appear in one clear view, without treating transfers as expenses.','visible':'visible','Movimientos completos':'Complete records','Ingresos, gastos, ahorros, préstamos, inversiones y transferencias.':'Income, expenses, savings, loans, investments, and transfers.','Todo se puede corregir':'Everything can be corrected','¿Ingresaste mal el monto o la fecha? Abrí el movimiento, cambiá el dato y guardalo en segundos. Tu cuenta se recalcula automáticamente.':'Entered the wrong amount or date? Open the transaction, change it, and save in seconds. Your balance updates automatically.','ANTES':'BEFORE','CORREGIDO':'CORRECTED','Instalá GeFi como aplicación y seguí registrando aunque no tengas datos o Wi-Fi.':'Install GeFi as an app and keep logging transactions without mobile data or Wi-Fi.','Hecha para vos':'Made for you','Idioma, moneda base, categorías, presupuestos y cuentas adaptados a tu manera de organizarte.':'Language, base currency, categories, budgets, and accounts adapted to the way you organize.',
    'GeFi por dentro':'Inside GeFi','Claridad en cada pantalla.':'Clarity on every screen.','Desde una frase hasta el reporte del mes. Cada vista está diseñada para que encuentres la información importante sin perder tiempo.':'From a simple sentence to your monthly report. Every view is designed to help you find what matters without wasting time.','Registrá y entendé':'Track and understand','Lenguaje natural, categorías y reportes en el mismo flujo.':'Natural language, categories, and reports in one flow.','Tu panorama completo':'Your complete overview','Montos ficticios utilizados únicamente para esta demostración.':'Sample amounts used only for this demonstration.','Un historial que se entiende':'A history you can understand','Ingresos, gastos e inversiones diferenciados visualmente.':'Income, expenses, and investments clearly distinguished.',
    'Demo de producto':'Product demo','GeFi en movimiento.':'GeFi in action.','Reproducí el recorrido para ver cómo un movimiento pasa de una frase cotidiana a un registro claro dentro de tu historial.':'Play the walkthrough to see how an everyday sentence becomes a clear record in your transaction history.','Reproducir demo':'Play demo','Video demostrativo interactivo de GeFi':'Interactive GeFi product demo','Capítulos de la demostración':'Demo chapters','Resumen':'Overview','Registro':'Entry','Corrección':'Correction','Reportes':'Reports','Historial':'History','PASO 1':'STEP 1','Tu panorama, de un vistazo':'Your overview, at a glance','Patrimonio, cuentas, efectivo e inversiones.':'Net worth, accounts, cash, and investments.','PASO 2':'STEP 2','Registrá en segundos':'Log it in seconds','¿Qué movimiento querés registrar?':'What transaction would you like to record?','Escribí o usá tu voz. GeFi organiza el resto.':'Type or use your voice. GeFi organizes the rest.','PASO 3':'STEP 3','Corregí cualquier error':'Correct any mistake','Modificar movimiento':'Edit transaction','Fecha':'Date','Monto':'Amount','Guardar cambios':'Save changes','Editá fecha, monto o detalle y el balance se actualiza.':'Edit the date, amount, or details and the balance updates.','PASO 4':'STEP 4','Entendé el mes':'Understand your month','Visualizá el flujo y los gastos por categoría.':'See cash flow and expenses by category.','PASO 5':'STEP 5','Todo queda claro':'Everything stays clear','Fecha, categoría, cuenta, monto y detalle.':'Date, category, account, amount, and details.','Reproducir demostración':'Play demonstration','Progreso de la demostración':'Demonstration progress','Reiniciar demostración':'Restart demonstration',
    'Empezá hoy':'Start today','Entender tu dinero':'Understanding your money','cambia lo que hacés con él.':'changes what you do with it.','Abrir GeFi gratis':'Open GeFi for free','Tu gestor financiero personal.':'Your personal finance manager.','Soporte':'Support','Aplicación':'App','GeFi, inicio':'GeFi, home','Resumen de ejemplo con patrimonio, cuentas, efectivo, ingresos, gastos e inversiones en GeFi':'Sample GeFi overview with net worth, accounts, cash, income, expenses, and investments','Ejemplo del registro inteligente y los reportes mensuales de GeFi en un teléfono':'Sample of GeFi smart entry and monthly reports on a phone','Resumen financiero de ejemplo de GeFi':'Sample GeFi financial overview','Historial de movimientos de ejemplo de GeFi':'Sample GeFi transaction history','Registro inteligente y reportes mensuales de GeFi':'GeFi smart entry and monthly reports','Resumen de ejemplo de GeFi':'Sample GeFi overview','Historial de ejemplo de GeFi':'Sample GeFi history'
  },
  pt: {
    'Saltar al contenido':'Pular para o conteúdo','Navegación principal':'Navegação principal','Funciones':'Recursos','Por qué registrar':'Por que registrar','Capturas':'Telas','Idioma':'Idioma','Seleccionar idioma':'Selecionar idioma','Cambiar tema':'Alterar tema','Abrir GeFi':'Abrir GeFi',
    'Finanzas personales, sin ruido':'Finanças pessoais, sem complicação','Tu dinero,':'Seu dinheiro,','con contexto.':'com contexto.','Registrá cada movimiento, entendé tus hábitos y tomá decisiones con información real. GeFi reúne todo lo que pasa con tu dinero en un solo lugar.':'Registre cada movimentação, entenda seus hábitos e tome decisões com informações reais. O GeFi reúne tudo o que acontece com seu dinheiro em um só lugar.','Empezar ahora':'Começar agora','Ver cómo funciona':'Ver como funciona','Características principales':'Principais recursos','Funciona sin conexión':'Funciona offline','Sin costo':'Gratuito','Datos bajo tu control':'Seus dados sob seu controle',
    'Vista real del resumen de GeFi':'Visão real do resumo do GeFi','Resumen financiero':'Resumo financeiro','Flujo del mes':'Fluxo do mês','Gráfico decorativo de evolución mensual':'Gráfico decorativo da evolução mensal','Todo actualizado':'Tudo atualizado','Balance visible':'Saldo visível','En todo momento':'A qualquer momento','Registro inteligente':'Registro inteligente','“Hoy gasté 2.000” ✓':'“Hoje gastei 2.000” ✓','Beneficios de GeFi':'Benefícios do GeFi','Una vista completa':'Uma visão completa','de tu patrimonio':'do seu patrimônio','Menos tiempo':'Menos tempo','cargando movimientos':'registrando movimentações','Más claridad':'Mais clareza','para decidir':'para decidir',
    'Lo que no registrás, no podés mejorarlo':'Você não pode melhorar o que não registra','Cada movimiento':'Cada movimentação','cuenta una historia.':'conta uma história.','Anotar no es controlar por controlar. Es convertir compras, ingresos y decisiones cotidianas en una imagen honesta de tu realidad financiera.':'Registrar não é controlar por controlar. É transformar compras, receitas e decisões cotidianas em uma imagem honesta da sua realidade financeira.','Dejá de adivinar':'Pare de adivinhar','Sabé cuánto tenés, dónde está y en qué se fue. Sin cuentas mentales ni saldos aislados.':'Saiba quanto você tem, onde está e para onde foi. Sem contas mentais ou saldos isolados.','Detectá hábitos':'Identifique hábitos','Los pequeños gastos repetidos dejan de ser invisibles.':'Pequenos gastos recorrentes deixam de ser invisíveis.','Medí tu progreso':'Meça seu progresso','Compará meses y entendé si tus decisiones te acercan a tus objetivos.':'Compare os meses e entenda se suas decisões aproximam você dos seus objetivos.','Decidí antes':'Decida antes','Presupuestos y reportes te ayudan a actuar antes de que un desorden se convierta en problema.':'Orçamentos e relatórios ajudam você a agir antes que uma desorganização se torne um problema.',
    'Todo conectado':'Tudo conectado','Una sola app.':'Um único app.','Toda tu economía.':'Toda a sua vida financeira.','Registrá con lenguaje natural':'Registre com linguagem natural','Escribí o dictá “hoy gasté 2.000 en el supermercado”. GeFi interpreta fecha, monto, categoría y detalle.':'Digite ou diga “hoje gastei 2.000 no supermercado”. O GeFi identifica data, valor, categoria e detalhes.','Hoy gasté 2.000 en el supermercado':'Hoje gastei 2.000 no supermercado','Enviar ejemplo':'Enviar exemplo','HOY':'HOJE','GASTO':'DESPESA','Todo tu patrimonio':'Todo o seu patrimônio','Cuentas, efectivo e inversiones se leen como una sola imagen, sin confundir transferencias con gastos.':'Contas, dinheiro e investimentos aparecem em uma única visão, sem confundir transferências com despesas.','visible':'visível','Movimientos completos':'Registros completos','Ingresos, gastos, ahorros, préstamos, inversiones y transferencias.':'Receitas, despesas, economias, empréstimos, investimentos e transferências.','Todo se puede corregir':'Tudo pode ser corrigido','¿Ingresaste mal el monto o la fecha? Abrí el movimiento, cambiá el dato y guardalo en segundos. Tu cuenta se recalcula automáticamente.':'Informou o valor ou a data errada? Abra a movimentação, altere o dado e salve em segundos. Seu saldo é recalculado automaticamente.','ANTES':'ANTES','CORREGIDO':'CORRIGIDO','Instalá GeFi como aplicación y seguí registrando aunque no tengas datos o Wi-Fi.':'Instale o GeFi como aplicativo e continue registrando mesmo sem dados móveis ou Wi-Fi.','Hecha para vos':'Feito para você','Idioma, moneda base, categorías, presupuestos y cuentas adaptados a tu manera de organizarte.':'Idioma, moeda base, categorias, orçamentos e contas adaptados à sua organização.',
    'GeFi por dentro':'Por dentro do GeFi','Claridad en cada pantalla.':'Clareza em cada tela.','Desde una frase hasta el reporte del mes. Cada vista está diseñada para que encuentres la información importante sin perder tiempo.':'De uma frase ao relatório mensal. Cada tela foi criada para você encontrar o que importa sem perder tempo.','Registrá y entendé':'Registre e entenda','Lenguaje natural, categorías y reportes en el mismo flujo.':'Linguagem natural, categorias e relatórios no mesmo fluxo.','Tu panorama completo':'Sua visão completa','Montos ficticios utilizados únicamente para esta demostración.':'Valores fictícios usados apenas nesta demonstração.','Un historial que se entiende':'Um histórico fácil de entender','Ingresos, gastos e inversiones diferenciados visualmente.':'Receitas, despesas e investimentos diferenciados visualmente.',
    'Demo de producto':'Demonstração do produto','GeFi en movimiento.':'GeFi em ação.','Reproducí el recorrido para ver cómo un movimiento pasa de una frase cotidiana a un registro claro dentro de tu historial.':'Reproduza o percurso para ver como uma frase cotidiana se transforma em um registro claro no seu histórico.','Reproducir demo':'Reproduzir demo','Video demostrativo interactivo de GeFi':'Demonstração interativa do GeFi','Capítulos de la demostración':'Capítulos da demonstração','Resumen':'Resumo','Registro':'Registro','Corrección':'Correção','Reportes':'Relatórios','Historial':'Histórico','PASO 1':'ETAPA 1','Tu panorama, de un vistazo':'Sua visão em um instante','Patrimonio, cuentas, efectivo e inversiones.':'Patrimônio, contas, dinheiro e investimentos.','PASO 2':'ETAPA 2','Registrá en segundos':'Registre em segundos','¿Qué movimiento querés registrar?':'Qual movimentação você quer registrar?','Escribí o usá tu voz. GeFi organiza el resto.':'Digite ou use sua voz. O GeFi organiza o restante.','PASO 3':'ETAPA 3','Corregí cualquier error':'Corrija qualquer erro','Modificar movimiento':'Editar movimentação','Fecha':'Data','Monto':'Valor','Guardar cambios':'Salvar alterações','Editá fecha, monto o detalle y el balance se actualiza.':'Edite data, valor ou detalhes e o saldo será atualizado.','PASO 4':'ETAPA 4','Entendé el mes':'Entenda o mês','Visualizá el flujo y los gastos por categoría.':'Veja o fluxo e as despesas por categoria.','PASO 5':'ETAPA 5','Todo queda claro':'Tudo fica claro','Fecha, categoría, cuenta, monto y detalle.':'Data, categoria, conta, valor e detalhes.','Reproducir demostración':'Reproduzir demonstração','Progreso de la demostración':'Progresso da demonstração','Reiniciar demostración':'Reiniciar demonstração',
    'Empezá hoy':'Comece hoje','Entender tu dinero':'Entender seu dinheiro','cambia lo que hacés con él.':'muda o que você faz com ele.','Abrir GeFi gratis':'Abrir GeFi gratuitamente','Tu gestor financiero personal.':'Seu gestor financeiro pessoal.','Soporte':'Suporte','Aplicación':'Aplicativo','GeFi, inicio':'GeFi, início','Resumen de ejemplo con patrimonio, cuentas, efectivo, ingresos, gastos e inversiones en GeFi':'Exemplo do resumo do GeFi com patrimônio, contas, dinheiro, receitas, despesas e investimentos','Ejemplo del registro inteligente y los reportes mensuales de GeFi en un teléfono':'Exemplo do registro inteligente e dos relatórios mensais do GeFi em um celular','Resumen financiero de ejemplo de GeFi':'Exemplo do resumo financeiro do GeFi','Historial de movimientos de ejemplo de GeFi':'Exemplo do histórico de movimentações do GeFi','Registro inteligente y reportes mensuales de GeFi':'Registro inteligente e relatórios mensais do GeFi','Resumen de ejemplo de GeFi':'Exemplo do resumo do GeFi','Historial de ejemplo de GeFi':'Exemplo do histórico do GeFi'
  }
};

Object.assign(translations.en,{
  'Patrimonio':'Net worth','+ 8,4% este mes':'+8.4% this month','Meta de ahorro':'Savings goal','Presupuesto':'Budget','$ 73.400 de $ 100.000':'$73,400 of $100,000',
  'Decisiones con contexto':'Decisions with context','Reportes visuales construidos a partir de cada movimiento registrado.':'Visual reports built from every recorded transaction.',
  'Seguí un caso de uso completo: Alex registra un ingreso, una compra y una inversión; después revisa cómo cambió su patrimonio.':'Follow a complete use case: Alex records income, a purchase, and an investment, then reviews how their net worth changed.',
  'Inicio':'Start','Ingreso':'Income','Gasto':'Expense','Inversión':'Investment','PASO 6':'STEP 6','Un punto de partida claro':'A clear starting point','Cuenta demostración':'Demo account','SALDO INICIAL':'STARTING BALANCE','Alex abre GeFi y ve su dinero disponible.':'Alex opens GeFi and sees the available balance.',
  'Registrá lo que entra':'Record money coming in','Hoy cobré 425.800 por honorarios':'I received 425,800 in fees today','+ $ 425.800 · Ingreso':'+ $425,800 · Income','GeFi reconoce el monto, la fecha y el tipo.':'GeFi recognizes the amount, date, and type.',
  'Anotá una compra':'Record a purchase','Hoy gasté 18.640 en el supermercado':'I spent 18,640 at the supermarket today','− $ 18.640 · Alimentos':'− $18,640 · Groceries','El gasto queda categorizado en segundos.':'The expense is categorized in seconds.',
  'Separá una inversión':'Set aside an investment','Hoy invertí 42.500 en un fondo índice':'I invested 42,500 in an index fund today','$ 42.500 · Inversión':'$42,500 · Investment','La inversión aumenta tu patrimonio, no tus gastos.':'The investment increases your net worth, not your expenses.',
  'Todo se actualiza':'Everything updates','Patrimonio, cuenta, gastos e inversiones quedan conectados.':'Net worth, account, expenses, and investments stay connected.','Revisá la historia completa':'Review the full story','Alex entiende qué entró, qué gastó y cuánto invirtió.':'Alex understands what came in, what was spent, and how much was invested.',
  'Cuenta ficticia de GeFi con patrimonio, ingresos, gastos e inversiones':'Fictional GeFi account with net worth, income, expenses, and investments','Ejemplo ficticio del registro inteligente y el historial de GeFi':'Fictional example of GeFi smart entry and history','Resumen financiero ficticio de GeFi':'Fictional GeFi financial overview','Reportes ficticios de ingresos, gastos e inversiones en GeFi':'Fictional GeFi income, expense, and investment reports','Resumen ficticio actualizado de GeFi':'Updated fictional GeFi overview','Reporte ficticio de movimientos de GeFi':'Fictional GeFi transaction report'
  ,'Modo oscuro, claridad intacta':'Dark mode, full clarity','La misma información financiera con una interfaz cómoda para ambientes con poca luz.':'The same financial information in a comfortable interface for low-light environments.','Panel de reportes de GeFi en modo oscuro con datos ficticios':'GeFi reports dashboard in dark mode with fictional data'
});
Object.assign(translations.pt,{
  'Patrimonio':'Patrimônio','+ 8,4% este mes':'+8,4% este mês','Meta de ahorro':'Meta de economia','Presupuesto':'Orçamento','$ 73.400 de $ 100.000':'$ 73.400 de $ 100.000',
  'Decisiones con contexto':'Decisões com contexto','Reportes visuales construidos a partir de cada movimiento registrado.':'Relatórios visuais criados a partir de cada movimentação registrada.',
  'Seguí un caso de uso completo: Alex registra un ingreso, una compra y una inversión; después revisa cómo cambió su patrimonio.':'Acompanhe um caso completo: Alex registra uma receita, uma compra e um investimento e depois vê como o patrimônio mudou.',
  'Inicio':'Início','Ingreso':'Receita','Gasto':'Despesa','Inversión':'Investimento','PASO 6':'ETAPA 6','Un punto de partida claro':'Um ponto de partida claro','Cuenta demostración':'Conta de demonstração','SALDO INICIAL':'SALDO INICIAL','Alex abre GeFi y ve su dinero disponible.':'Alex abre o GeFi e vê o dinheiro disponível.',
  'Registrá lo que entra':'Registre o que entra','Hoy cobré 425.800 por honorarios':'Hoje recebi 425.800 por serviços','+ $ 425.800 · Ingreso':'+ $ 425.800 · Receita','GeFi reconoce el monto, la fecha y el tipo.':'O GeFi reconhece o valor, a data e o tipo.',
  'Anotá una compra':'Registre uma compra','Hoy gasté 18.640 en el supermercado':'Hoje gastei 18.640 no supermercado','− $ 18.640 · Alimentos':'− $ 18.640 · Alimentação','El gasto queda categorizado en segundos.':'A despesa é categorizada em segundos.',
  'Separá una inversión':'Separe um investimento','Hoy invertí 42.500 en un fondo índice':'Hoje investi 42.500 em um fundo de índice','$ 42.500 · Inversión':'$ 42.500 · Investimento','La inversión aumenta tu patrimonio, no tus gastos.':'O investimento aumenta seu patrimônio, não suas despesas.',
  'Todo se actualiza':'Tudo se atualiza','Patrimonio, cuenta, gastos e inversiones quedan conectados.':'Patrimônio, conta, despesas e investimentos ficam conectados.','Revisá la historia completa':'Veja a história completa','Alex entiende qué entró, qué gastó y cuánto invirtió.':'Alex entende o que entrou, o que gastou e quanto investiu.',
  'Cuenta ficticia de GeFi con patrimonio, ingresos, gastos e inversiones':'Conta fictícia do GeFi com patrimônio, receitas, despesas e investimentos','Ejemplo ficticio del registro inteligente y el historial de GeFi':'Exemplo fictício do registro inteligente e histórico do GeFi','Resumen financiero ficticio de GeFi':'Resumo financeiro fictício do GeFi','Reportes ficticios de ingresos, gastos e inversiones en GeFi':'Relatórios fictícios de receitas, despesas e investimentos no GeFi','Resumen ficticio actualizado de GeFi':'Resumo fictício atualizado do GeFi','Reporte ficticio de movimientos de GeFi':'Relatório fictício de movimentações do GeFi'
  ,'Modo oscuro, claridad intacta':'Modo escuro, clareza preservada','La misma información financiera con una interfaz cómoda para ambientes con poca luz.':'As mesmas informações financeiras em uma interface confortável para ambientes com pouca luz.','Panel de reportes de GeFi en modo oscuro con datos ficticios':'Painel de relatórios do GeFi em modo escuro com dados fictícios'
});

const textSources = new Map();
const attributeSources = new Map();
const walker = document.createTreeWalker(body, NodeFilter.SHOW_TEXT, { acceptNode: node => node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT });
while (walker.nextNode()) textSources.set(walker.currentNode, walker.currentNode.nodeValue);
document.querySelectorAll('*').forEach(element => { const values={}; ['aria-label','title','alt','placeholder'].forEach(attribute=>{if(element.hasAttribute(attribute))values[attribute]=element.getAttribute(attribute)});if(Object.keys(values).length)attributeSources.set(element,values) });
const pageMetadata = {
  es:{title:'GeFi | Gestor Financiero',description:'GeFi es un gestor financiero personal para registrar movimientos, entender tus hábitos y decidir con información real.'},
  en:{title:'GeFi | Personal Finance Manager',description:'GeFi is a personal finance manager for tracking transactions, understanding your habits, and making informed decisions.'},
  pt:{title:'GeFi | Gestor Financeiro Pessoal',description:'GeFi é um gestor financeiro pessoal para registrar movimentações, entender seus hábitos e tomar decisões informadas.'}
};
function translateValue(source, language) { if(language==='es')return source;const leading=source.match(/^\s*/)[0],trailing=source.match(/\s*$/)[0],value=source.trim();return `${leading}${translations[language][value]||value}${trailing}`; }
function setLanguage(language, persist=true) { const supported=['es','en','pt'],next=supported.includes(language)?language:'es';document.documentElement.lang=next;textSources.forEach((source,node)=>{node.nodeValue=translateValue(source,next)});attributeSources.forEach((values,element)=>Object.entries(values).forEach(([attribute,source])=>element.setAttribute(attribute,translateValue(source,next))));document.title=pageMetadata[next].title;document.querySelector('meta[name="description"]').content=pageMetadata[next].description;document.querySelector('meta[property="og:title"]').content=pageMetadata[next].title;document.querySelector('meta[property="og:description"]').content=pageMetadata[next].description;document.querySelector('.language-select').value=next;if(persist)localStorage.setItem('gefi-site-language',next); }
const detectedLanguage=localStorage.getItem('gefi-site-language')||((navigator.languages||[navigator.language]).find(language=>/^pt/i.test(language))?'pt':(navigator.languages||[navigator.language]).find(language=>/^en/i.test(language))?'en':'es');
setLanguage(detectedLanguage,false);
document.querySelector('.language-select').addEventListener('change',event=>setLanguage(event.target.value));

const themeButton = document.querySelector('.theme-toggle');
const preferredTheme = localStorage.getItem('gefi-site-theme');
if (preferredTheme === 'dark' || (!preferredTheme && matchMedia('(prefers-color-scheme: dark)').matches)) body.classList.add('dark');
themeButton.addEventListener('click', () => { body.classList.toggle('dark'); localStorage.setItem('gefi-site-theme', body.classList.contains('dark') ? 'dark' : 'light'); });

const reveals = document.querySelectorAll('.reveal');
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .12 });
reveals.forEach(item => observer.observe(item));

const slides=[...document.querySelectorAll('.demo-slide')],chapterButtons=[...document.querySelectorAll('.demo-chapters button')],playButtons=[document.querySelector('.player-play'),document.querySelector('.demo-external-play')],restartButton=document.querySelector('.player-restart'),timeline=document.querySelector('.timeline'),progress=timeline.querySelector('span'),scrubber=timeline.querySelector('i'),time=document.querySelector('.player-controls time');
let playing=false,startedAt=0,elapsed=0,animationFrame;const duration=36000,slideDuration=duration/slides.length;
const formatTime=value=>`00:${String(Math.floor(value/1000)).padStart(2,'0')}`;
function showSlide(index){slides.forEach((slide,position)=>slide.classList.toggle('active',position===index));chapterButtons.forEach((button,position)=>{button.classList.toggle('active',position===index);button.setAttribute('aria-selected',String(position===index))})}
function updateDemo(){const ratio=Math.min(1,elapsed/duration),slideIndex=Math.min(slides.length-1,Math.floor(elapsed/slideDuration));showSlide(slideIndex);progress.style.width=`${ratio*100}%`;scrubber.style.left=`${ratio*100}%`;timeline.setAttribute('aria-valuenow',String(Math.round(elapsed/1000)));time.textContent=`${formatTime(elapsed)} / 00:36`}
function renderDemo(now){if(!playing)return;elapsed=Math.min(duration,now-startedAt);updateDemo();if(elapsed>=duration){playing=false;document.querySelector('.player-play').textContent='▶';return}animationFrame=requestAnimationFrame(renderDemo)}
function toggleDemo(){if(elapsed>=duration)elapsed=0;playing=!playing;document.querySelector('.player-play').textContent=playing?'❚❚':'▶';if(playing){startedAt=performance.now()-elapsed;animationFrame=requestAnimationFrame(renderDemo);document.querySelector('#demo').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})}else cancelAnimationFrame(animationFrame)}
function seek(nextElapsed,autoplay=false){cancelAnimationFrame(animationFrame);elapsed=Math.max(0,Math.min(duration,nextElapsed));updateDemo();playing=autoplay;if(playing){document.querySelector('.player-play').textContent='❚❚';startedAt=performance.now()-elapsed;animationFrame=requestAnimationFrame(renderDemo)}else document.querySelector('.player-play').textContent='▶'}
playButtons.forEach(button=>button.addEventListener('click',toggleDemo));restartButton.addEventListener('click',()=>seek(0,true));chapterButtons.forEach((button,index)=>button.addEventListener('click',()=>seek(index*slideDuration,true)));
timeline.addEventListener('click',event=>{const bounds=timeline.getBoundingClientRect();seek((event.clientX-bounds.left)/bounds.width*duration,playing)});timeline.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();seek(elapsed+3000,playing)}if(event.key==='ArrowLeft'){event.preventDefault();seek(elapsed-3000,playing)}});updateDemo();
